MarketsList = [
  {
    "name": "Fan tokens",
    "type": 'Markets',
    "extraProfitPerHour": "2.62k",
    "costToUpgrade": 7253630,
  },
  {
    "name": "Staking",
    "type": 'Markets',
    "extraProfitPerHour": "1.77k",
    "costToUpgrade": 5818908,
  },
  {
    "name": "BTC pairs",
    "type": 'Markets',
    "extraProfitPerHour": 110,
    "costToUpgrade": 181341,
  },
  {
    "name": "ETH pairs",
    "type": 'Markets',
    "extraProfitPerHour": 118,
    "costToUpgrade": 498764,
  },
  {
    "name": "Top 10 cmc pairs",
    "type": 'Markets',
    "extraProfitPerHour": 221,
    "costToUpgrade": 725363,
  },
  {
    "name": "GameFi tokens",
    "type": 'Markets',
    "extraProfitPerHour": 207,
    "costToUpgrade": 831273,
  },
  {
    "name": "Defi2.0 tokens",
    "type": 'Markets',
    "extraProfitPerHour": 110,
    "costToUpgrade": 362681,
  },
  {
    "name": "SocialFi tokens",
    "type": 'Markets',
    "extraProfitPerHour": 138,
    "costToUpgrade": 362681,
  },
  {
    "name": "Meme coins",
    "type": 'Markets',
    "extraProfitPerHour": 303,
    "costToUpgrade": 1450726,
  },
  {
    "name": "Shit coins",
    "type": 'Markets',
    "extraProfitPerHour": "1.63k",
    "costToUpgrade": 3626815,
  },
  {
    "name": "Margin trading x10",
    "type": 'Markets',
    "extraProfitPerHour": 759,
    "costToUpgrade": 1813407,
  },
  {
    "name": "Margin trading x20",
    "type": 'Markets',
    "extraProfitPerHour": 966,
    "costToUpgrade": 1813407,
  },
  {
    "name": "Margin trading x30",
    "type": 'Markets',
    "extraProfitPerHour": "1.48k",
    "costToUpgrade": 5818908,
  },
  {
    "name": "Margin trading x50",
    "type": 'Markets',
    "extraProfitPerHour": "3.04k",
    "costToUpgrade": 7253630,
  },
  {
    "name": "Margin trading x75",
    "type": 'Markets',
    "extraProfitPerHour": "3.04k",
    "costToUpgrade": 5440222,
  },
  {
    "name": "Margin trading x100",
    "type": 'Markets',
    "extraProfitPerHour": "2.88k",
    "costToUpgrade": 8312726,
  },
  {
    "name": "Derivatives",
    "type": 'Markets',
    "extraProfitPerHour": "1.46k",
    "costToUpgrade": 4156363,
  },
  {
    "name": "Prediction markets",
    "type": 'Markets',
    "extraProfitPerHour": "1.09k",
    "costToUpgrade": 7001948,
  },
  {
    "name": "Web3 integration",
    "type": 'Markets',
    "extraProfitPerHour": "2.18k",
    "costToUpgrade": 4714859,
  },
  {
    "name": "DAO",
    "type": 'Markets',
    "extraProfitPerHour": 679,
    "costToUpgrade": 1662545,
  },
  {
    "name": "P2P trading",
    "type": 'Markets',
    "extraProfitPerHour": "1.08k",
    "costToUpgrade": 3046524,
  },
  {
    "name": "Trading bots",
    "type": 'Markets',
    "extraProfitPerHour": 538,
    "costToUpgrade": 1523262,
  },
   {
    "name": "LayerZero Listing",
    "type": 'Markets',
    "extraProfitPerHour": "2.48k",
    "costToUpgrade": 7253630,
  },
]

PRandTeamList = [
  {
    "name": "Support team",
    "type": 'PR&Team',
    "extraProfitPerHour": 193,
    "costToUpgrade": 544022,
  },
  {
    "name": "HamsterBook",
    "type": 'PR&Team',
    "extraProfitPerHour": 193,
    "costToUpgrade": 362681,
  },
  {
    "name": "X",
    "type": 'PR&Team',
    "extraProfitPerHour": 221,
    "costToUpgrade": 398950,
  },
  {
    "name": "Cointelegraph",
    "type": 'PR&Team',
    "extraProfitPerHour": 118,
    "costToUpgrade": 581891,
  },
  {
    "name": "HamsterTube",
    "type": 'PR&Team',
    "extraProfitPerHour": 248,
    "costToUpgrade": 435218,
  },
  {
    "name": "HamsterGram",
    "type": 'PR&Team',
    "extraProfitPerHour": 158,
    "costToUpgrade": 2000557,
  },
  {
    "name": "TikTok",
    "type": 'PR&Team',
    "extraProfitPerHour": 276,
    "costToUpgrade": 544022,
  },

  {
    "name": "Coindesk",
    "type": 'PR&Team',
    "extraProfitPerHour": 221,
    "costToUpgrade": 725363,
  },
  {
    "name": "Influencers",
    "type": 'PR&Team',
    "extraProfitPerHour": 745,
    "costToUpgrade": 1813407,
  },
  {
    "name": "CEO",
    "type": 'PR&Team',
    "extraProfitPerHour": 276,
    "costToUpgrade": 725363,
  },
  {
    "name": "IT team",
    "type": 'PR&Team',
    "extraProfitPerHour": 662,
    "costToUpgrade": 1450726,
  },
  {
    "name": "Marketing",
    "type": 'PR&Team',
    "extraProfitPerHour": 193,
    "costToUpgrade": 725363,
  },
  {
    "name": "Partnership program",
    "type": 'PR&Team',
    "extraProfitPerHour": 193,
    "costToUpgrade": 362681,
  },
  {
    "name": "Product team",
    "type": 'PR&Team',
    "extraProfitPerHour": 276,
    "costToUpgrade": 725363,
  },
  {
    "name": "Bisdev team",
    "type": 'PR&Team',
    "extraProfitPerHour": 138,
    "costToUpgrade": 362681,
  },
  {
    "name": "Two factor authentication",
    "type": 'PR&Team',
    "extraProfitPerHour": 345,
    "costToUpgrade": 725363,
  },
  {
    "name": "UX and UI team",
    "type": 'PR&Team',
    "extraProfitPerHour": 517,
    "costToUpgrade": 1263534,
  },
  {
    "name": "Security team",
    "type": 'PR&Team',
    "extraProfitPerHour": 590,
    "costToUpgrade": 1662545,
  },
  {
    "name": "QA team",
    "type": 'PR&Team',
    "extraProfitPerHour": 524,
    "costToUpgrade": 924838,
  },
  {
    "name": "Antihacking shield",
    "type": 'PR&Team',
    "extraProfitPerHour": 303,
    "costToUpgrade": 1450726,
  },
  {
    "name": "Risk management team",
    "type": 'PR&Team',
    "extraProfitPerHour": 731,
    "costToUpgrade": 1450726,
  },
  {
    "name": "Security Audition",
    "type": 'PR&Team',
    "extraProfitPerHour": 276,
    "costToUpgrade": 2176089,
  },
  {
    "name": "Anonymous transaction ban",
    "type": 'PR&Team',
    "extraProfitPerHour": 886,
    "costToUpgrade": 1496291,
  },
  {
    "name": "Blocking suspicious accounts",
    "type": 'PR&Team',
    "extraProfitPerHour": 441,
    "costToUpgrade": 906704,
  },
  {
    "name": "Tokenomics experts",
    "type": 'PR&Team',
    "extraProfitPerHour": "1.38k",
    "costToUpgrade": 3626815,
  },
  {
    "name": "Consensus Exprorer pass",
    "type": 'PR&Team',
    "extraProfitPerHour": "3.87k",
    "costToUpgrade": 8307428,
  },
  {
    "name": "VC Labs",
    "type": 'PR&Team',
    "extraProfitPerHour": "1.21k",
    "costToUpgrade": 2477529,
  },
  {
    "name": "Compliance officer",
    "type": 'PR&Team',
    "extraProfitPerHour": 289,
    "costToUpgrade": 559442,
  },
  {
    "name": "Welcome to Amsterdam",
    "type": 'PR&Team',
    "extraProfitPerHour": 897,
    "costToUpgrade": 2176089,
  },
  {
    "name": "Development Hub Mumbai",
    "type": 'PR&Team',
    "extraProfitPerHour": "10.31k",
    "costToUpgrade": 29906742,
  },
  {
    "name": "Data Center Tokyo",
    "type": 'PR&Team',
    "extraProfitPerHour": "15.66k",
    "costToUpgrade": 31968120,
  },
  {
    "name": "Leaderboards",
    "type": 'PR&Team',
    "extraProfitPerHour": "1.81k",
    "costToUpgrade": 3196812,
  },
]

LegalList = [
  {
    "name": "KYC",
    "type": 'Legal',
    "extraProfitPerHour": 28,
    "costToUpgrade": 72536,
  },
  {
    "name": "KYB",
    "type": 'Legal',
    "extraProfitPerHour": 166,
    "costToUpgrade": 362681,
  },
  {
    "name": "Legal opinion",
    "type": 'Legal',
    "extraProfitPerHour": 166,
    "costToUpgrade": 725363,
  },
  {
    "name": "SEC transparancy",
    "type": 'Legal',
    "extraProfitPerHour": 177,
    "costToUpgrade": 1995054,
  },
  {
    "name": "Anti money loundering",
    "type": 'Legal',
    "extraProfitPerHour": 773,
    "costToUpgrade": 2176089,
  },
  {
    "name": "Licence UAE",
    "type": 'Legal',
    "extraProfitPerHour": "1.55k",
    "costToUpgrade": 3626815,
  },
  {
    "name": "Licence Europe",
    "type": 'Legal',
    "extraProfitPerHour": "2.13k",
    "costToUpgrade": 8312726,
  },
  {
    "name": "Licence Asia",
    "type": 'Legal',
    "extraProfitPerHour": "1.02k",
    "costToUpgrade": 3626815,
  },
  {
    "name": "Licence South America",
    "type": 'Legal',
    "extraProfitPerHour": "1.08k",
    "costToUpgrade": 3626815,
  },
  {
    "name": "Licence Australia",
    "type": 'Legal',
    "extraProfitPerHour": "1.88k",
    "costToUpgrade": 3626815,
  },
  {
    "name": "Licence North America",
    "type": 'Legal',
    "extraProfitPerHour": "2.65k",
    "costToUpgrade": 7253630,
  },
  {
    "name": "Licence Nigeria",
    "type": 'Legal',
    "extraProfitPerHour": 469,
    "costToUpgrade": 1088044,
  },
  {
    "name": "Licence Japan",
    "type": 'Legal',
    "extraProfitPerHour": "6.7k",
    "costToUpgrade": 16614856,
  },
  {
    "name": "Licence Ethiopia",
    "type": 'Legal',
    "extraProfitPerHour": "4.64k",
    "costToUpgrade": 11630400,
  },
  {
    "name": "Licence India",
    "type": 'Legal',
    "extraProfitPerHour": "6.45k",
    "costToUpgrade": 14953371,
  },
  {
    "name": "Licence Bangladesh",
    "type": 'Legal',
    "extraProfitPerHour": "9.03k",
    "costToUpgrade": 23260799,
  },
  {
    "name": "Licence Indonesia",
    "type": 'Legal',
    "extraProfitPerHour": "12.89k",
    "costToUpgrade": 33229713,
  },
  {
    "name": "Licence Vietnam",
    "type": 'Legal',
    "extraProfitPerHour": "10.31k",
    "costToUpgrade": 28245256,
  },
  {
    "name": "Licence turkey",
    "type": 'Legal',
    "extraProfitPerHour": "7.23k",
    "costToUpgrade": 11988045,
  },
  {
    "name": "Licence Philippines",
    "type": 'Legal',
    "extraProfitPerHour": "17.93k",
    "costToUpgrade": 108804444,
  },
]

SpecialList = [
  {
    "name": "DEX",
    "type": 'web3',
    "extraProfitPerHour": "7.23k",
    "costToUpgrade": 11988045,
  },
  {
    "name": "Oracle",
    "type": 'web3',
    "extraProfitPerHour": "1.93k",
    "costToUpgrade": 2797211,
  },
  {
    "name": "Vesting Smartcontracts",
    "type": 'web3',
    "extraProfitPerHour": "2.06k",
    "costToUpgrade": 350843,
  },
  # {
  #   "name": "Sports Integration",
  #   "type": 'special',
  #   "extraProfitPerHour": "7.74k",
  #   "costToUpgrade": 11630400,
  # },
  {
    "name": "Percussion Taps",
    "type": 'special',
    "extraProfitPerHour": "3.87k",
    "costToUpgrade": 6645943,
  },
  {
    "name": "CX Hub Istanbul",
    "type": 'special',
    "extraProfitPerHour": "7.74k",
    "costToUpgrade": 18276342,
  },
  {
    "name": "Hamster break records",
    "type": 'special',
    "extraProfitPerHour": "5.41k",
    "costToUpgrade": 11919950,
  },
  # {
  #   "name": "web3 game con",
  #   "type": 'special',
  #   "extraProfitPerHour": "3.09k",
  #   "costToUpgrade": 9968914,
  # },
  {
    "name": "X network 10 million",
    "type": 'special',
    "extraProfitPerHour": "1.03k",
    "costToUpgrade": 2326080,
  },
  {
    "name": "Hamster Green Energy",
    "type": 'special',
    "extraProfitPerHour": "5.52k",
    "costToUpgrade": 12331170,
  },
  {
    "name": "Your tube 25 million",
    "type": 'special',
    "extraProfitPerHour": "6.2k",
    "costToUpgrade": 29925813,
  },
  {
    "name": "TG Leaders",
    "type": 'special',
    "extraProfitPerHour": "7.27k",
    "costToUpgrade": 88024491,
  }, 
  {
    "name": "Premarket Launch",
    "type": 'special',
    "extraProfitPerHour": "15.79k",
    "costToUpgrade": 42813036,
  },
  {
    "name": "Hamster combat merch",
    "type": 'special',
    "extraProfitPerHour": 276,
    "costToUpgrade": 2176089,
  }, 
  {
    "name": "TON + hamster Kombat = Success",
    "type": 'special',
    "extraProfitPerHour": "9.84k",
    "costToUpgrade": 23839901,
  },
  {
    "name": "Consensus Piranha Pass",
    "type": 'special',
    "extraProfitPerHour": "4.58k",
    "costToUpgrade": 7992030,
  },
  {
    "name": "Web3 academy launch",
    "type": 'special',
    "extraProfitPerHour": "4.14k",
    "costToUpgrade": 7978993,
  },
  {
    "name": "Youtube Gold Button",
    "type": 'special',
    "extraProfitPerHour": 812,
    "costToUpgrade": 4156363,
  },
  {
    "name": "Hamster Youtube Channel",
    "type": 'special',
    "extraProfitPerHour": 690,
    "costToUpgrade": 1088044,
  },
  {
    "name": "Bitcoin Pizza Day",
    "type": 'special',
    "extraProfitPerHour": 276,
    "costToUpgrade": 725363,
  },
  {
    "name": "Top 10 Global Ranking",
    "type": 'special',
    "extraProfitPerHour": "3.54k",
    "costToUpgrade": 16625452,
  },
  {
    "name": "NFT Collection Launch",
    "type": 'special',
    "extraProfitPerHour": "3.09k",
    "costToUpgrade": 5649051,
  },

  {
    "name": "Special Hamster Conference",
    "type": 'special',
    "extraProfitPerHour": "2.84k",
    "costToUpgrade": 20005566,
  },
  {
    "name": "Short squeeze",
    "type": 'special',
    "extraProfitPerHour": "2.58k",
    "costToUpgrade": 11630400,
  },
  {
    "name": "There are two chairs...",
    "type": 'special',
    "extraProfitPerHour": "4.82k",
    "costToUpgrade": 7992030,
  },
  {
    "name": "Long squeeze",
    "type": 'special',
    "extraProfitPerHour": "5.52k",
    "costToUpgrade": 21760889,
  },
  {
    "name": "Villa for the DEV team",
    "type": 'special',
    "extraProfitPerHour": "1.33k",
    "costToUpgrade": 3325090,
  },
  {
    "name": "Apps Center Listing",
    "type": 'special',
    "extraProfitPerHour": "2.58k",
    "costToUpgrade": 4984457,
  },
  {
    "name": "Bogdanov is calling",
    "type": 'special',
    "extraProfitPerHour": "1.31k",
    "costToUpgrade": 3626815,
  },
  {
    "name": "USDT on TON",
    "type": 'special',
    "extraProfitPerHour": "3.73k",
    "costToUpgrade": 7253630,
  },
]